import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable()
export class EmailFacade {
  constructor(private readonly httpClient: HttpClient) {}

  sendEmail(address: string, reportLocation: string) {
    // Todo lowerCamel case not working
    // Make plaint text and html content optional
    return this.httpClient.post(
      'https://webemail.azurewebsites.net/api/Email?code=3GGXFIqO5Xx86oKASZRitGXu8q0fl3YuvSmlkAMuEfa9tJW78xBTbw==',
      {
        To: address,
        Subject: 'Setup Sheet',
        HtmlContent: `Setup sheet generated by MySetupSheet.com: <a href="${reportLocation}">Open Setup Sheet</a>`,
        PlainTextContent: 'remove this as required'
      }
    );
  }
}
